export const adottati_db = [
  {
    id: "Smile",
    nome: "Smile",
    images: [
      "/images/adottati/smile/smile1.jpg",
      "/images/adottati/smile/smile2.jpg",
      "/images/adottati/smile/smile3.jpg",
    ],
    taglia: "media",
    anno_di_nascita: "2024",
    mese_di_nascita: "7",
    sesso: "Maschio",
    descrizione:
      "Smile è uno cagnolino vivace e affettuoso. Adora correre all’aria aperta e giocare con la palla. È molto socievole sia con le persone che con altri animali. Luna cerca una famiglia che la riempia di amore e attenzioni.",
    sverminato: true,
    microchip: true,
    vaccinato: true,
    sterilizzato: true,
    adozione_mese: "1",
    adozione_anno: "2025",
  },
  {
    id: "Leo",
    nome: "Leo",
    images: [
      "/images/adottati/leo/leo1.jpg",
      "/images/adottati/leo/leo2.jpg",
      "/images/adottati/leo/leo3.jpg",
      "/images/adottati/leo/leo4.jpg",
    ],
    taglia: "grande",
    anno_di_nascita: "2017",
    mese_di_nascita: "11",
    sesso: "Maschio",
    descrizione:
      "Leo è un cane energico e protettivo, ideale per chi ama le lunghe passeggiate nella natura. È intelligente e impara in fretta, perfetto per chi vuole un compagno di avventure. Leo si affeziona molto alle persone ed è un ottimo cane da famiglia.",
    sverminato: true,
    microchip: true,
    vaccinato: true,
    sterilizzato: true,
    adozione_mese: "6",
    adozione_anno: "2024",
  },
  {
    id: "Mia",
    nome: "Mia",
    images: [
      "/images/adottati/mia/mia1.jpg",
      "/images/adottati/mia/mia2.jpg",
      "/images/adottati/mia/mia3.jpg",
      "/images/adottati/mia/mia4.jpg",
      "/images/adottati/mia/mia5.jpg",
    ],
    taglia: "media",
    anno_di_nascita: "2021",
    mese_di_nascita: "3",
    sesso: "Femmina",
    descrizione:
      "Mia è dolce e paziente, perfetta per chi cerca un cane tranquillo e affettuoso. Adora stare in compagnia e si integra facilmente in qualsiasi ambiente. Va d'accordo con bambini e altri animali, rendendola una compagna ideale per tutta la famiglia.",
    sverminato: true,
    microchip: true,
    vaccinato: true,
    sterilizzato: false,
    adozione_mese: "12",
    adozione_anno: "2023",
  },
];
